apiVersion: apps/v1
kind: Deployment
metadata:
  name: ta9ss-deployment
spec:
  replicas: 3 # Increased to 3 for better High Availability
  selector:
    matchLabels:
      app: ta9ss
  template:
    metadata:
      labels:
        app: ta9ss
    spec:
      containers:
      - name: ta9ss
        image: youssefkazdar/ta9ss:latest
        resources: # SECURITY: Prevent the app from consuming all server RAM
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
        livenessProbe: # K8S SELF-HEALING: Restarts container if it crashes
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: ta9ss-service
spec:
  type: NodePort
  selector:
    app: ta9ss
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30001